---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloknative
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: helloknative
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
